/**
 * What "ready" means, expressed as data rather than as an opinion.
 *
 * Shipyard's job is not to build software — the coding agent does that. Its job
 * is to know whether what got built is safe to put in front of anyone, and to
 * be able to show its working. That means three things have to be facts rather
 * than judgements: what the user is trying to make, what that obliges them to
 * have, and what has actually been observed.
 *
 * An agent that says "done" is not evidence. A passing test is.
 */

/**
 * How far this build is going.
 *
 * The single most important field in the system. Everything downstream keys off
 * it: which rules apply, which gates are required, what score counts as ready,
 * and whether a failure is a blocker or a note. Asking it first is what stops a
 * weekend prototype being treated as a product with customers on it.
 */
export type TargetMode =
  /** Screens to look at and click through. Dummy data is expected, not a flaw. */
  | 'ui_concept'
  /** The core workflow really works. Integrations may still be pretend. */
  | 'functional_prototype'
  /** A controlled group of real people use it for real. */
  | 'customer_pilot'
  /** A commercial product strangers depend on. */
  | 'production_product';

/**
 * The modes in increasing order of obligation.
 *
 * Exported because "this rule applies at customer_pilot and above" is the most
 * common thing a rule needs to say, and expressing it as a list of modes gets
 * out of date the moment a mode is added.
 */
export const TARGET_MODE_ORDER: readonly TargetMode[] = [
  'ui_concept',
  'functional_prototype',
  'customer_pilot',
  'production_product',
];

/** Is `mode` at least as demanding as `floor`? */
export function modeAtLeast(mode: TargetMode, floor: TargetMode): boolean {
  return TARGET_MODE_ORDER.indexOf(mode) >= TARGET_MODE_ORDER.indexOf(floor);
}

/**
 * Facts about the project that change what it owes its users.
 *
 * Every one of these is a question a founder can answer about their own
 * business. None of them requires knowing what a migration is.
 */
export interface ProjectIntent {
  targetMode: TargetMode;
  /** Free-form classification, e.g. `recruitment_workflow_saas`. */
  projectType?: string;
  /** Where the users are. Drives privacy obligations. */
  regions: string[];
  /** Personal data beyond an email address: identity, health, finance, files. */
  sensitiveData: boolean;
  /** Money changes hands inside the product. */
  payments: boolean;
  /**
   * The software decides something that materially affects a person — who gets
   * hired, lent to, admitted, or refused.
   */
  aiAffectsConsequentialDecision: boolean;
  /** A person reviews those decisions before they take effect. */
  humanReviewRequired: boolean;
  /** Anyone on the internet can reach it. */
  publicFacing: boolean;
  expectedMonthlyUsers?: number;
  /** ISO date. */
  launchDateTarget?: string;
  existingCodeSource: 'new_project' | 'imported';
}

/** The boolean facts a rule can test, as names rather than as a closure. */
export type IntentFlag =
  | 'sensitiveData'
  | 'payments'
  | 'aiAffectsConsequentialDecision'
  | 'humanReviewRequired'
  | 'publicFacing';

export type Severity =
  /** Cannot launch at the chosen mode until this is satisfied. */
  | 'blocker'
  /** Should be dealt with, and the user may knowingly proceed. */
  | 'warning'
  /** Worth doing. Never gates anything. */
  | 'recommendation';

export type GateStatus =
  | 'passed'
  | 'failed'
  /** Required, and nothing has been observed yet. */
  | 'pending'
  /** Deliberately not required at this mode. */
  | 'skipped';

/**
 * One observation about the project, from something other than the agent.
 *
 * `observedAt` matters as much as `status`: evidence goes stale. A test that
 * passed against code from three releases ago is not evidence about this one.
 */
export interface Evidence {
  gateId: string;
  status: GateStatus;
  /** ISO 8601. */
  observedAt: string;
  /** One line, shown to the user when a gate fails. */
  summary?: string;
  /** Where to look: a verification run, an incident, a deployment. */
  ref?: string;
}

/** What a rule demands when it applies. */
export interface RuleRequirement {
  /** Verification gates that must pass. */
  gates?: string[];
  /** Components that must be installed and verified. */
  components?: string[];
  /** A person has to sign this off, whatever the gates say. */
  humanReview?: boolean;
  /** Paid-service offers this rule justifies, if it is not satisfied. */
  serviceTriggers?: string[];
}

/**
 * A launch rule.
 *
 * Deliberately data, not code: the whole point is that "is this ready" has an
 * answer that can be read, argued with, versioned and tested, rather than being
 * regenerated by a model each time somebody asks.
 */
export interface Rule {
  id: string;
  version: number;
  category:
    | 'mode'
    | 'security'
    | 'privacy'
    | 'payments'
    | 'deployment'
    | 'observability'
    | 'testing'
    | 'escalation';
  /** All conditions present must hold for the rule to apply. */
  when: {
    /** Applies at this mode and every more demanding one. */
    minMode?: TargetMode;
    /** Applies only at exactly these modes. */
    modeIn?: TargetMode[];
    factsTrue?: IntentFlag[];
    factsFalse?: IntentFlag[];
    /** Every listed capability must be in the project. */
    capabilities?: string[];
  };
  require: RuleRequirement;
  severity: Severity;
  /**
   * What the user reads. Written as a consequence for their product, not as a
   * technical instruction: "customers will be able to see each other's data",
   * not "RBAC tests are absent".
   */
  message: string;
}

/** What evaluating one rule against one project produced. */
export interface RuleOutcome {
  ruleId: string;
  ruleVersion: number;
  category: Rule['category'];
  severity: Severity;
  message: string;
  /** False when the rule's conditions did not match this project at all. */
  applies: boolean;
  /** True when every gate it requires has passed. */
  satisfied: boolean;
  requiredGates: string[];
  /** Required gates that have not passed: failed, pending, or never run. */
  missingGates: string[];
  requiredComponents: string[];
  humanReviewRequired: boolean;
  serviceTriggers: string[];
}
